ministryofjustice/analytics-platform-ops

- k8s-templates/jupyter-notebook/deployment.yml
This will be used in the oauth-proxy container to check the logged user
is the same user as the owner of the containter.
> Setting USER variable in jupyter/oauth-proxy container

- k8s-templates/jupyter-notebook/deployment.yml
See: https://github.com/ministryofjustice/analytics-platform-rstudio-auth-proxy/pull/1
> Jupyter deployment to use new proxy image with authorisation

- infra/terraform/modules/data_buckets/iam.tf
From the AWS documentation:
> To list all buckets, users require the GetBucketLocation and ListAllMyBuckets actions for all resources in Amazon S3
Unfortunately **this will show the users all the buckets** (but they'll only
have access to the source/scratch one). From some of the comments on the
internet show only some of the buckets was not supported (yet).
But there may be a solution for this.
See: https://aws.amazon.com/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/
Ticket: https://trello.com/c/yKYfs7cf
> Users can list buckets in AWS Console (S3 policies)

- infra/terraform/modules/data_buckets/iam.tf
I tested the upload with a user with only the 'analytics-managers' or
'analytics-analysts' role and they couldn't upload files.
They also need to perform the `s3:PutObjectAcl` action.
> S3: Fixed permission problem preventing upload

- infra/terraform/env-dev/main.tf
- infra/terraform/modules/data_buckets/main.tf
- infra/terraform/modules/lambda_functions/encrypt_s3_object/index.js
- infra/terraform/modules/lambda_functions/encrypt_s3_object/package.json
- infra/terraform/modules/lambda_functions/inputs.tf
- infra/terraform/modules/lambda_functions/main.tf
4 terraform resources are needed:
- The lambda function itself
- The role running the lambda function
- The notification from the S3 bucket when an S3 object is created
- The permission for the bucket to invoke the lambda function
I automated the lambda function packaging by using terraform's [`data "archive_file"`](https://www.terraform.io/docs/providers/archive/d/archive_file.html). The `aws_lambda_function` resource depends on it. This resource has also a `source_code_hash` attribute with its value depending on the zip archive file (to force a re-deploy when the lambda function change).
> Added AWS lambda to encrypt S3 objects after upload

- infra/terraform/modules/lambda_functions/encrypt_s3_object/index.js
- infra/terraform/modules/lambda_functions/main.tf
Using S3's headObject() rather than getObject() to improve the performances.
There is a [spreadsheet with the times](https://docs.google.com/a/digital.justice.gov.uk/spreadsheets/d/1LntDAdTFKpnOT_37tjVraPdZ_cVQLBu-xdrn14jay5o/edit?usp=sharing) the lambda function takes depending on the file size.
> Improved performance of AWS Lambda to encrypt S3 objects

- infra/terraform/environments/alpha/main.tf
- infra/terraform/environments/dev/main.tf
- infra/terraform/environments/example/main.tf
- infra/terraform/modules/lambda_functions/inputs.tf
- infra/terraform/modules/lambda_functions/main.tf
For example the `alpha` environment will have an `alpha_encrypt_s3_object` lambda function in it.
I also added this terraform module to the example and alpha environments.
> Create a separate AWS lambda function per environment

- jenkinsfiles/deploy_rstudio_for_user.groovy
- k8s-templates/r-studio-user/deployment.yml
See: ministryofjustice/analytics-platform-rstudio#2
Also updated Jenkins `deploy_rstudio_for_user` job to set `AWS_DEFAULT_REGION` which is needed by cloudyr (and maybe other libraries).
**NOTE**: I didn't put the `AWS_DEFAULT_REGION` value in a k8s secret as this is not really a secret so base64 it seemed overkill.
> RStudio: Use docker image with Cloudyr preinstalled

- charts/rstudio/Chart.yaml
- charts/rstudio/templates/deployment.yml
This is to set the `AWS_DEFAULT_REGION` environment variable for the user
See: https://github.com/ministryofjustice/analytics-platform-rstudio/pull/3
> RStudio Chart: Bump docker image version

- jenkinsfiles/grant_access_to_app.groovy
* Removed python virtualenv setup steps
* Refactored credentials access
* Invoke `grant_access` python script now preinstalled on jenkins build image
1. Run the `grant-access-to-app` job on Control Panel Jenkins
2. Tail the console output
3. See that no virtualenv or pip setup is done
4. See that user is granted access
See [Fix flaky grant-access job so it succeeds every time](https://trello.com/c/MRa2uwrz)
> Use Python script installed on build agent image

- jenkinsfiles/grant_access_to_app.groovy
* Move build parameters into Jenkinsfile
* Call updated python script with list of email addresses
1. Run the `grant-access-to-app` Control Panel Jenkins job
2. See the parameters are now "APP_NAME" and "EMAILS"
3. Enter multiple email addresses separated by semicolons (`;`)
4. See the job run
5. See users with the given email addresses have been granted access to the specified app
See [Enable user to provide semicolon delimited list of email addresses as part of the Jenkins grant-access job](https://trello.com/c/L5cA87Mn)
> Enable adding multiple users at once

- infra/terraform/environments/alpha/main.tf
Tried to run `$ terraform plan` in the `alpha` environment but it complained about the missing `dns_zone_id` variable in the `logging_elasticsearch` module (as part of [Kerin's work on ES](https://github.com/ministryofjustice/analytics-platform-ops/pull/47))
1. Run `$ terraform plan`
2. Does it return an error?
3. If not this fixes the problem
> Terraform alpha env: Pass `dns_zone_id` to `logging_elasticsearch` module

- infra/terraform/modules/data_access/github_webhooks_handler/github_webhooks.py
- infra/terraform/modules/data_access/github_webhooks_handler/tests/test_publish_to_sns.py
The GH Webhooks handler don't process the GH events directly but rather submit them to AWS SNS for later processing.
So respond with a `202 ACCEPTED` is more appropriate.
See GOV.UK's Style [Guidelines on API](https://github.com/alphagov/styleguides/blob/master/api.md):
> Use 202 for times when the data is valid, but we've queued
> the persistence for background processing, as described in
> RFC 7231:
> "The request has been accepted for processing, but the
> processing has not been completed.
> GH Webhooks handler responds 202 ACCEPTED as it should.

- infra/terraform/modules/data_access/topics.tf
When members will be added to the organisation we'll create a corresponding
IAM role for them.
**Ticket**: https://trello.com/c/vYuW5G7n/115-create-sns-queues-for-each-github-event-type-we-re-interested-in-user-joined-left-org-team-created-user-joined-left-team
> Added SNS topic: ${ENV}_github_organization_events

- infra/terraform/environments/dev/main.tf
- infra/terraform/modules/data_access/inputs.tf
- infra/terraform/modules/data_access/lambda_assume_role_policy_document.tf
- infra/terraform/modules/data_access/lambda_organization_events.tf
- infra/terraform/modules/data_access/lambda_users.tf
- infra/terraform/modules/data_access/organization_events/organization_events.py
- infra/terraform/modules/data_access/organization_events/requirements.dev.txt
- infra/terraform/modules/data_access/organization_events/tests/conftest.py
- infra/terraform/modules/data_access/organization_events/tests/test_organization_events.py
- infra/terraform/modules/data_access/users/requirements.dev.txt
- infra/terraform/modules/data_access/users/tests/conftest.py
- infra/terraform/modules/data_access/users/tests/test_create_user_role.py
- infra/terraform/modules/data_access/users/tests/test_delete_user_role.py
- infra/terraform/modules/data_access/users/users.py
- infra/terraform/modules/notifications/outputs.tf
This is to handle the organization GitHub events arriving from the corresponding SNS topic (`${ENV}_github_organization_events`)
These events are handled by the `organization_events` "controller" lambda function which then invoke the `create_user_role`/`delete_user_role` asyncrounously.
**NOTE**: The `delete_user_role` lambda function has to detach all the role's policies before being able to delete it.
Part of ticket: https://trello.com/c/UZ8qooqO/116-xl-create-lambda-functions-to-consume-github-events-from-sns-queues-and-create-update-delete-aws-resources
> Handle GitHub "organization" events to add/remove IAM roles in AWS

- infra/terraform/modules/data_access/lambda_organization_events.tf
- infra/terraform/modules/data_access/organization_events/organization_events.py
- infra/terraform/modules/data_access/organization_events/tests/conftest.py
- infra/terraform/modules/data_access/organization_events/tests/test_organization_events.py
- infra/terraform/modules/data_access/users/tests/conftest.py
- infra/terraform/modules/data_access/users/tests/test_create_user_role.py
- infra/terraform/modules/data_access/users/tests/test_delete_user_role.py
- Using `str#encode` instead of `bytes()`
- Renamed environment variables to be explicit about the fact
these ARNs belongs to lambda functions
- Moved module documentation at the beginning of the file
- Using `getLogger(__name__)` instead of `__package__`
- Inline lambda functions payload instead of having it in a
function
- Removed some of the tests fixtures and used pytest's parametrize
to remove some duplication
See [PR #62: Handle GitHub "organization" events to add/remove IAM roles in AWS](https://github.com/ministryofjustice/analytics-platform-ops/pull/62#pullrequestreview-40250908)
> Amendments to as per Andy comments (PR #62)

- infra/terraform/modules/data_access/lambda_team_events.tf
- infra/terraform/modules/data_access/lambda_teams.tf
- infra/terraform/modules/data_access/teams/teams.py
- infra/terraform/modules/data_access/teams/tests/conftest.py
- infra/terraform/modules/data_access/teams/tests/test_create_team_bucket_policies.py
This lambda function will create a read-only IAM policy and a read/write IAM policy.
The read-only policy has the following permissions:
- list buckets in AWS console
- list objects in the team bucket
- read objects in the team bucket
The read/write policy has all the permissions in the read-only one plus:
- can delete/rename/update/restore objects and their ACL in the team bucket
This lambda function is invoked asyncronously by the `team_event`
lambda when a team is created.
When a user will later be added to this team, the right policy will be attached to his role:
- read-only if 'member'
- read/write if 'owner' or 'mainteiner'
https://trello.com/c/UZ8qooqO/116-(xl)-create-lambda-functions-to-consume-github-events-from-sns-queues-and-create%2Fupdate%2Fdelete-aws-resources
> Add lambda function to create team bucket policies

- infra/terraform/modules/data_access/lambda_team_events.tf
- infra/terraform/modules/data_access/lambda_teams.tf
- infra/terraform/modules/data_access/teams/teams.py
- infra/terraform/modules/data_access/teams/tests/conftest.py
- infra/terraform/modules/data_access/teams/tests/test_delete_team_bucket_policies.py
When a team is deleted in GitHub we want the corresponding S3 bucket
policies to be deleted, but not the bucket itself which may still
contain important data.
Delete a policy is not as straightforward as it sounds unfortunately
because it needs to be detached from roles, groups and users first
([See AWS documentation](https://docs.aws.amazon.com/de_de/IAM/latest/APIReference/API_DeletePolicy.html))
https://trello.com/c/UZ8qooqO/116-(xl)-create-lambda-functions-to-consume-github-events-from-sns-queues-and-create%2Fupdate%2Fdelete-aws-resources
> Add lambda function to delete team bucket policies

- infra/terraform/environments/dev/main.tf
- infra/terraform/modules/data_access/inputs.tf
- infra/terraform/modules/data_access/lambda_users.tf
- infra/terraform/modules/data_access/users/tests/conftest.py
- infra/terraform/modules/data_access/users/users.py
Updated code to:
1. `data_access` module use `saml_provider_arn` output variable from `federated_identity` module instead of hardcoding the SAML provider ARN
2. Removed `_role` suffix from generated roles to adhere with [Auth0 rule](https://github.com/ministryofjustice/analytics-platform-auth0/blob/dev/rules/aws-saml-role-mapping.js#L3-L17) used to generate role assumed on login.
[Adds AWS Auth0 identity provider](https://github.com/ministryofjustice/analytics-platform-ops/pull/69)
> SAML integration

- jenkinsfiles/grant_access_to_app.groovy
Use Auth0 credentials per environment (dev, alpha) - standardised credentials names across jenkins CI and control panel jenkins.
> Use per-env Auth0 credentials

- infra/terraform/environments/dev/main.tf
- infra/terraform/modules/data_access/inputs.tf
- infra/terraform/modules/data_access/lambda_membership_events.tf
- infra/terraform/modules/data_access/membership_events/membership_events.py
- infra/terraform/modules/data_access/membership_events/tests/conftest.py
- infra/terraform/modules/data_access/membership_events/tests/test_membership_events.py
Handles events coming from GitHub/membership SNS topic.
These are published when a user is added/removed to/from a team in
GitHub:
- If a user is added to a group, we attach the corresponding bucket policy
to this user's role
- If a user is removed to a group, we detach the corresponding bucket policy
from this user's role
These two operations are actually performed by two independent lambda
functions injected via the `LAMBDA_ATTACH_BUCKET_POLICY_ARN` and
`LAMBDA_DETACH_BUCKET_POLICY_ARN` environment variables.
**NOTE**: These lambda functions currently don't exist and I'll update the
terraform resources later to pass the actual ARNs. This shouldn't change
the logic.
Surprising GitHub webhook membership events payload don't include the user
role for the team where is added. And also, no …
> Add lambda function to handle GitHub membership events

- jenkinsfiles/create_user.groovy
Change create_user Jenkins job to use new python script which checks that user is a member of the moj-analytical-services organization
See [https://trello.com/c/jlT5g9DC](Bugfix: Ensure user is part of analytical services org as part of deployment)
> Use python create_user script installed on docker image

- infra/terraform/environments/dev/main.tf
- infra/terraform/modules/data_access/inputs.tf
- infra/terraform/modules/data_access/lambda_users.tf
- infra/terraform/modules/data_access/users/tests/conftest.py
- infra/terraform/modules/data_access/users/users.py
Allow users' IAM roles to be assumed by EC2 instances
This is to allow [kube2iam](https://github.com/jtblin/kube2iam#iam-roles) to
attach these roles to the users' EC2 instances.
https://trello.com/c/v1RDtzeB/230-s-fix-dataaccess-iam-roles-trust-relationship
> Allow users' IAM roles to be assumed by EC2 instances

- circle.yml
- infra/terraform/environments/alpha/main.tf
- infra/terraform/modules/data_access/lambda_membership_events.tf
- infra/terraform/modules/data_access/lambda_memberships.tf
- infra/terraform/modules/data_access/membership_events/membership_events.py
- infra/terraform/modules/data_access/membership_events/tests/conftest.py
- infra/terraform/modules/data_access/membership_events/tests/test_membership_events.py
- infra/terraform/modules/data_access/memberships/memberships.py
- infra/terraform/modules/data_access/memberships/tests/conftest.py
- infra/terraform/modules/data_access/memberships/tests/test_attach_bucket_policy.py
- infra/terraform/modules/data_access/memberships/tests/test_detach_bucket_policies.py
- infra/terraform/modules/data_access/organization_events/tests/test_organization_events.py
- infra/terraform/modules/data_access/team_events/tests/test_team_events.py
- infra/terraform/modules/data_access/teams/teams.py
- infra/terraform/modules/data_access/teams/tests/conftest.py
- infra/terraform/modules/data_access/test.sh
- infra/terraform/modules/data_access/users/tests/conftest.py
- infra/terraform/modules/data_access/users/users.py
Invoked when a member is added to a team.
Attaches the specified IAM team bucket policy to the corresponding user role (e.g. `readonly` or `readwrite`).
Detaches all the IAM team bucket policies (`readonly` and `readwrite`) from the user role.
One subtle thing to notice here is that a given role would probably have only one of the currently available IAM policies (e.g. `readwrite` only). As AWS raises an exception when trying to detach a policy which is not attached, we need to be sure that we handle it and continue to detach all the IAM team bucket policies from the role.
https://trello.com/c/UZ8qooqO/116-xl-create-lambda-functions-to-consume-github-events-from-sns-queues-and-create-update-delete-aws-resources
> Add lambda functions to attach/detach IAM policies to/from IAM roles

- infra/terraform/modules/data_access/lambda_memberships.tf
- infra/terraform/modules/data_access/lambda_teams.tf
- infra/terraform/modules/data_access/lambda_users.tf
- infra/terraform/modules/data_access/memberships/memberships.py
- infra/terraform/modules/data_access/memberships/tests/conftest.py
- infra/terraform/modules/data_access/teams/teams.py
- infra/terraform/modules/data_access/teams/tests/conftest.py
- infra/terraform/modules/data_access/teams/tests/test_create_team_bucket_policies.py
- infra/terraform/modules/data_access/users/tests/conftest.py
- infra/terraform/modules/data_access/users/tests/test_create_user_role.py
- infra/terraform/modules/data_access/users/users.py
They don't add much value at the moment and the R library we currently use
(Cloudyr) is ignoring them causing problems.
The IAM role names will now be in the format `$ENV_user_$USERNAME`.
The IAM policies will also lose the path but their name doesn't change.
https://trello.com/c/8hp1cSPd/229-s-get-right-of-users-path-in-dataaccess-iam-roles
> Remove path from IAM roles and policies

- infra/terraform/environments/alpha/main.tf
- infra/terraform/environments/dev/main.tf
- infra/terraform/modules/data_access/inputs.tf
- infra/terraform/modules/data_access/lambda_teams.tf
- infra/terraform/modules/data_access/teams/teams.py
- infra/terraform/modules/data_access/teams/tests/conftest.py
- infra/terraform/modules/data_access/teams/tests/test_create_team_bucket.py
- infra/terraform/modules/data_buckets/main.tf
- infra/terraform/modules/data_buckets/s3.tf
Each bucket created by the team bucket lambda function requires access logs to be enabled. These changes ensure that all buckets created from github events have logging configured to send logs to a per-environment bucket, with an `s3/team-bucket-name/` prefix, to keep S3 logs separate from future CloudTrail logs, and to keep bucket logs separate from each other.
1. Terraform apply
2. Create a team bucket via github or the Lambda console
3. Check that logging is enabled via the S3 console, or:
4. Upload a file to the team bucket and verify that logs are created (may take up to 1 hour)
> Add S3 logging setup to team bucket creation lambda function

- charts/shiny-app/templates/deployment.yaml
- charts/shiny-app/values.yaml
I'm see this error in Jenkins and it's likely caused by the fact that
the `AuthProxy.AuthenticationRequired` value is `true` (boolean) instead of
`"true"` (string)
Error:
Error: UPGRADE FAILED: error validating "": error validating data: expected type string, for field spec.template.spec.containers[0].env[7].value, got bool
Part of https://trello.com/c/UVgHMv1C/223-l-allow-ip-based-access-control-to-shiny-apps-for-dom1-quantum-etc-instead-of-or-as-well-as-user-based-access-controls
> Shiny helm chart: Fix for "upgrade failed expected string got bool"

- jenkinsfiles/grant_access_to_app.groovy
The `APP_NAME` parameter is just the app name, not the whole URL. Changing
the wording to add an example and avoid confusion as suggested by Robin.
> Grant Access jenkins job: Improved wording to avoid confusion

- infra/terraform/modules/data_access/lambda_memberships.tf
- infra/terraform/modules/data_access/lambda_teams.tf
- infra/terraform/modules/data_access/lambda_users.tf
- infra/terraform/modules/data_access/memberships/.gitignore
- infra/terraform/modules/data_access/memberships/memberships.py
- infra/terraform/modules/data_access/users/.gitignore
We now catch this specific exception and retry twice after a brief amount of
time (200ms, tested). This prevent the lambda failing and the error to get
to us unless can't be handled this way.
Because of the asyncronous nature of these lambda functions, when creating
a new team or the user is new to the organisation:
1) The team bucket's IAM policy may not be created yet
2) The user's IAM role may not be created yet
In these two cases the `attach_bucket_policy` lambda function would raise
an [`NoSuchEntity` exception](https://sentry.service.dsd.io/mojds/data-access-lambda/issues/5251/events/146927/).
AWS will automatically retry and succeed but we'll be notified about this
error via Sentry.
Add a retry/sleep is not the pretties thing but:
1) From my manual experiments I've noticed that …
> attach_bucket_policy lambda function retries twice before notifying Sentry

- infra/terraform/environments/alpha/main.tf
Same as 9808ea95871b407d2bb65fa2c4099881ef5585f2 but in `alpha` environment
Without this `terraform plan` in `alpha` will fail.
> Terraform: Fixed S3 logs bucket references (in alpha env)

- infra/terraform/global/main.tf
- infra/terraform/modules/aws_account_logging/cloudtrail-lambda.tf
- infra/terraform/modules/aws_account_logging/cloudtrail/.gitignore
- infra/terraform/modules/aws_account_logging/cloudtrail/cloudtrail_to_es.py
- infra/terraform/modules/aws_account_logging/cloudtrail/requirements.txt
- infra/terraform/modules/aws_account_logging/main.tf
- Cloudtrail logs `sourceIPAddress` sometimes contains a hostname rather than an IP address, which causes errors with Elasticsearch, so don't use the pipeline in those cases
- Exclude Cloudtrail digest files from lambda function trigger
> Fix cloudtrail logs geoip pipeline and errors with digest files

- infra/terraform/environments/alpha/main.tf
- infra/terraform/environments/dev/main.tf
- infra/terraform/modules/control_panel_role/inputs.tf
- infra/terraform/modules/control_panel_role/outputs.tf
- infra/terraform/modules/control_panel_role/role.tf
IAM role assumed by the Control Panel API instances and grant them permissions to perform all the required operations:
- create S3 buckets
- create IAM policies to access them
- delete IAM policies
- attach IAM policies to user/app roles (to grant them access to an S3
bucket)
- detach IAM policies (to revoke user/app access to an S3 bucket)
- can create users/apps IAM roles
- can delete users/apps IAM roles
- Used by helm chart: https://github.com/ministryofjustice/analytics-platform-helm-charts/pull/16
- cpanel helm chart config: https://github.com/ministryofjustice/analytics-platform-config/pull/8
https://trello.com/c/AULNJYns/359-add-iam-role-for-control-panel-api-app-to-terraform
> Add IAM role for Control Panel API

- infra/terraform/environments/alpha/main.tf
- infra/terraform/environments/dev/main.tf
- infra/terraform/modules/control_panel_api/inputs.tf
- infra/terraform/modules/control_panel_api/role.tf
The `control_panel_api` IAM role wasn't assumed by the control panel API
instances. The problem was a missing statement with the k8s workers role
ARN as principal.
This is necessary in order for kube2iam to work as expected (see below)
See kube2iam documentation on assume role/trust relationship the IAM role needs:
https://github.com/jtblin/kube2iam#iam-roles
https://trello.com/c/hSOlOUmE/391-cp-api-bug-unable-to-locate-aws-credentials
> Fix control_panel_api IAM role

- infra/terraform/modules/data_access/lambda_memberships.tf
- infra/terraform/modules/data_access/lambda_users.tf
Two of the lambda functions' zips which must include some dependences
were not depending on the `null_resource` which install them.
This can *potentially* cause the installation to happen *after* the zip
is created, which therefore will miss these dependences.
Possible solution to https://trello.com/c/MpBnZkQx/548-lambda-function-i-o-error-5
> Lambda functions zips depends on script which install dependences

- infra/terraform/modules/control_panel_api/role.tf
CP-API will create S3 bucket with encryption enabled by default.
In order to do this, it will make a request to 'PUT Bucket encryption'
which requires the `s3:PutEncryptionConfiguration` permission.
**NOTE**: This may not be necessary as according to the documentation the bucket
owner has this permission, but can't see who is the owner from the AWS console.
https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html#using-with-s3-actions-related-to-bucket-subresources
https://trello.com/c/NJsrt6fe/584-2-enable-bucket-level-encryption-for-user-created-buckets
> CP-API role can s3:PutEncryptionConfiguration

- infra/terraform/modules/control_panel_api/role.tf
This is necessary for IAM roles revamp to work:
https://github.com/ministryofjustice/analytics-platform-control-panel/pull/88
After this changes CP-API will need to read and write IAM roles' inline policies which requires `iam:GetRolePolicy` and `iam:PutRolePolicy`.
Part of https://trello.com/c/2nuxrwiq/586-5-iam-policies-change-from-1-per-bucket-to-1-per-user
> Control Panel IAM role can read/write roles' inline policies

- infra/terraform/modules/control_panel_api/role.tf
This enables the new call to put bucket tagging on a 'data warehouse' bucket.
Related to PR on api https://github.com/ministryofjustice/analytics-platform-control-panel/pull/93
> Add s3:PutBucketTagging

- infra/terraform/modules/control_panel_api/role.tf
The [migration which adds the OIDC statement to the users' roles trust policies](https://github.com/ministryofjustice/analytics-platform-control-panel/pull/90) will need the `iam:GetRole` and `iam:UpdateAssumeRolePolicy` permissions to read/update them.
**NOTE**: This will be needed *only* before running the migration.
After running the migration we can remove them.
In fact, there is no point in merging this, better just apply off this branch.
https://trello.com/c/Vy7ImBcn/602-4-sso-aws-federated-login-user-roles-migration
> (TEMPORARY) CP-API role permission to read/update users roles trust policies

- scripts/helm_redeploy_init-user.sh
Trello: https://trello.com/c/1h5t0me5
Simple script to redeploy the init-user helm chart.
Will delete the rstudio and jupyter releases belonging to the user as the resources for those releases will be removed by deleting the init-user release.
1. `kubectl config use-context < Your Dev cluster context >
2.  Ensure the directory you're in has both [Helm Charts](https://github.com/ministryofjustice/analytics-platform-helm-charts) and [Chart Config](https://github.com/ministryofjustice/analytics-platform-config) repos cloned to it.
3. Run the script `./helm_redeploy_init-user.sh`
> Init-User Chart Redeploy script

- infra/terraform/modules/control_panel_api/role.tf
Added permission to `iam:ListPolicies` to `control_panel_api` IAM role
This is needed by the [migration](https://github.com/ministryofjustice/analytics-platform-control-panel/pull/109/files#diff-7c3ac2e9db789dd8ece232021649f51aR38) which reads IAM policies and
creates the corresponding S3 buckets in the Control Panel API DB.
- [migration PR](https://github.com/ministryofjustice/analytics-platform-control-panel/pull/109)
- [IAM documentation at iam.cloudonaut.io](https://iam.cloudonaut.io/reference/iam.html)
https://trello.com/c/Me2RD6ek/696-5-script-that-copies-data-access-permissions-from-existing-lambda-created-policies-to-to-s3-access-inline-policy-and-adds-these
> Add permission to list IAM policies to control_panel IAM role

- infra/terraform/modules/control_panel_api/db.tf
- Set retention period to 35 days
- Set backup window between 10pm and midnight (everyday)
- Set maintenance window Saturday night between 1am and 3am
- Do **not** skip final snapshot. When an RDS instance is destroyed
(by accident of for whatever reason) AWS will take a final snapshot.
This can be really useful.
**NOTE**: I also set PostgreSQL version to 9.6.6 as this is the version which
the RDS instance is actually using!
> Enable backups for CP-API database

- infra/terraform/modules/control_panel_api/role.tf
CP-API's IAM role can now perform the following operations:
- [`iam:ListRolePolicies`](https://iam.cloudonaut.io/reference/iam/ListRolePolicies.html) - to lists the names of the inline policies that are embedded in the specified IAM role.
- [`iam:DeleteRolePolicy`](https://iam.cloudonaut.io/reference/iam/DeleteRolePolicy.html) - Deletes the specified inline policy that is embedded in the specified IAM role.
This is required by the CP-API to delete all the inline policies
of a user/app IAM role before deleting it.
Delete users in the CP didn't work because now most IAM roles have the
`s3-access` inline policy.
https://github.com/ministryofjustice/analytics-platform-control-panel/pull/175
https://trello.com/c/04FsXha3/984-cant-delete-users …
> Granting CP-API IAM role permission to list/delete inline policies

- infra/terraform/modules/lambda_mgmt/CHANGELOG.md
- infra/terraform/modules/lambda_mgmt/README.md
- infra/terraform/modules/lambda_mgmt/cloudwatch.tf
- infra/terraform/modules/lambda_mgmt/iam.tf
- infra/terraform/modules/lambda_mgmt/lambda.tf
- infra/terraform/modules/lambda_mgmt/variables.tf
Done as part of [Trello](https://trello.com/c/DAeTcJoT)
Module for provisioning Lambda functions
Default runtime `Golang`
IAM policies to be passed in at module invocation
I've already deployed this but to kind of test do:
1. `git checkout ebs-backups`
2. `terraform workspace new test-lambda`
3. `terraform init`
4. `terraform plan -target=module.kubernetes_etcd_ebs_snapshot`
5. See: [README](https://github.com/ministryofjustice/analytics-platform-ops/pull/139/files#diff-4a0623065a272190f6672c2feb083203) for an example of how to implement
> Lambda Module

- infra/terraform/modules/lambda_mgmt/README.md
- infra/terraform/modules/lambda_mgmt/lambda.tf
- infra/terraform/modules/lambda_mgmt/variables.tf
Forgot to push these changes with the last merge.  
Defining the terraform variables block at invocation allows the module to be more generic as
terraform cannot interpolate terraform variables as keys to environment variables.
The module has an empty map passed to the environment block which is expecting a map.
The map will then be populated when the module is invoked elsewhere with there own custom environment variables.  See the [README](https://github.com/ministryofjustice/analytics-platform-ops/blob/e36f76bbf00dc5bb6a469a72dcaa1b7b4a0ab8ed/infra/terraform/modules/lambda_mgmt/README.md) for an example
This has already been deployed and works.
> Lambda Module environment variables

- infra/elasticsearch/README.md
Elastic have removed __kopf__ in favor of the __API Console__ (Not
happy about that)
Updating docs to reflect the change.
Adding __list__ queries which are useful to have to hand
> Elasticsearch Console

- infra/terraform/environments/alpha/main.tf
- infra/terraform/environments/dev/main.tf
What
====
Airflow DB instance types were `t2.micro` (512 MiB of memory).
Now using `db.m3.medium` which has 3.75 GiB (on both `dev` and `alpha`).
See: https://aws.amazon.com/rds/instance-types/
Why
===
Even with relatively trivial DAGs with 30-60 tasks running concurrently
we were seeing some errors relative to DB connections.
It seemed like the DB dropped connections after ~32.
The `max_connections` depends on the amount of memory the RDS instance has,
specifically:
max_connections = DBInstanceClassMemory / 12582880
So 3.75GiB will give us a `max_connections` of ~320.
See: https://serverfault.com/a/862418
> (S) Airflow's RDS instances with more memory

- infra/elasticsearch/templates/cloudtrail.json
- infra/elasticsearch/templates/s3logs.json
These templates are using an invalid type to map data to.
Supported types are strings,floats,booleans,object,etc....
__Object__ seemed the best fit as it catches all.
This has been deployed
> Invalid Mapping

- infra/terraform/global/main.tf
- infra/terraform/global/outputs.tf
- infra/terraform/modules/ses_domain/inputs.tf
- infra/terraform/modules/ses_domain/main.tf
- infra/terraform/modules/ses_domain/outputs.tf
The SES resources were created manually in the AWS Console rather than using Terraform.
This PR imports these resources so that they're managed by Terraform.
> Imported SES resources for root domain

- infra/terraform/modules/ses_smtp_user/inputs.tf
- infra/terraform/modules/ses_smtp_user/main.tf
- infra/terraform/modules/ses_smtp_user/outputs.tf
- infra/terraform/platform/main.tf
- infra/terraform/platform/outputs.tf
The `ses_smtp_user` can be used to create an IAM user with
permission to send emails from the specified SES Domain Identity.
**NOTE**: The SMTP password for the user is not specified but it's
an output of the IAM Access Key associated with the IAM user
Luckily terraform's [`iam_access_key` has an attribute to get hold of the SMTP password](https://www.terraform.io/docs/providers/aws/r/iam_access_key.html#ses_smtp_password) without having to do anything weird.
Ticket: https://trello.com/c/tTZ1DG3y/1322-fix-airflow-email-notifications
> Added SES SMTP user for Airflow

- infra/terraform/modules/data_upload_user/iam.tf
update the /modules/data_upload_user/iam.tf file so that the writeonly account can push files to mojap-land bucket.
> upated iam s3 policy to write files into MOJAP-LAND

- scripts/fix_idled_ingress_class.sh
this script fixes ingresses in a bad state for idled rstudio instances.
If the ingress object for the user is still enabled but they are idled then they
can never be un-idled because the request will try to reach their pod instead of
the unidler.
This script loops through all idled deployments and then gets the corresponding
ingress object, the object is then checked for having an nginx ingress class
annotation. If it has this annotation then it is changed to 'disabled'
> Idled Ingress Class fixer

- .gitignore
- README.md
- infra/terraform/global/assets/create_etcd_ebs_snapshot/README.md
- infra/terraform/global/assets/prune_ebs_snapshots/README.md
Use a docker container to compile the go code.
Without doing these steps you get errors like this when running the global terraform:
```
$ terraform plan
Error: Error refreshing state: 2 error(s) occurred:
* data.archive_file.kubernetes_prune_ebs_snapshots_code: 1 error(s) occurred:
* data.archive_file.kubernetes_prune_ebs_snapshots_code: data.archive_file.kubernetes_prune_ebs_snapshots_code: error archiving file: could not archive missing file: assets/prune_ebs_snapshots/prune_ebs_snapshots
* data.archive_file.kubernetes_etcd_ebs_snapshot_code: 1 error(s) occurred:
* data.archive_file.kubernetes_etcd_ebs_snapshot_code: data.archive_file.kubernetes_etcd_ebs_snapshot_code: error archiving file: could not archive missing file: assets/create_etcd_ebs_snapshot/create_etcd_ebs_snapshot
``` …
> Improved instructions for lambda go compilation

- infra/terraform/global/cloudtrail.tf
- infra/terraform/global/main.tf
- infra/terraform/global/variables.tf
- infra/terraform/modules/aws_account_logging/main.tf
- infra/terraform/modules/aws_account_logging/s3.tf
Bucket names can't be fixed, since they are in a global namespace and other orgs running their copy of the platform will therefore need different names.
Run terraform plan to check contiguity. (CI does this anyway I believe)
> Make a couple of bucket names configurable

- infra/terraform/modules/data_backup/s3.tf
- infra/terraform/modules/data_buckets/crest.tf
- infra/terraform/modules/data_buckets/s3.tf
I don't know why these buckets aren't SSE in the terraform (the others are). And I don't know how they stayed encrypted on S3. Anyway, this PR stops terraform plan saying this:
```
cd infra/terraform/platform
terraform plan -var-file=vars/$ENVNAME.tfvars
...
~ module.data_backup.aws_s3_bucket.nfs_backup
server_side_encryption_configuration.#:                                                                "1" => "0"
server_side_encryption_configuration.0.rule.#:                                                         "1" => "0"
server_side_encryption_configuration.0.rule.0.apply_server_side_encryption_by_default.#:               "1" => "0"
server_side_encryption_configuration.0.rule.0.apply_server_side_encryption_by_default.0.sse_algorithm: "AES256" => ""
~ …
```
> Mark 4 buckets as SSE encrypted, as they are on dev & alpha

- README.md
* "Working with an existing environment" section felt redundant since you have to do 'terraform init' and once you add all the info about that you have duplicated most of the info in the preceding section. So I've combined the section.
* Difficulty switching backends was a trap I fell into several times, so I've explained about that. If there is a better way than deleting the .terraform dir then I'd love to know it. Adding `-backend=true` didn't do it.
* "You can usually ignore these actions" lists account for less-than-ideal terraform things, which fire every time. If we can fix these up then we can delete them from the list. Listing them means one less thing for the user to worry about, when they are editing things in other areas and run terraform.
* `ses_ap_email_identity_arn` param …
> Terraform docs improved

- infra/terraform/modules/data_backup/s3.tf
expired_object_delete_marker isn't allowed to be true when expiration is enabled. AWS resists this setting and therefore the rule fires every time you run `terraform plan`, which is annoying & confusing.
```
~ module.data_backup.aws_s3_bucket.nfs_backup
lifecycle_rule.0.expiration.3731869058.date:                                                           "" => ""
lifecycle_rule.0.expiration.3731869058.days:                                                           "" => "90"
lifecycle_rule.0.expiration.3731869058.expired_object_delete_marker:                                   "" => "true"
lifecycle_rule.0.expiration.4042355233.date:                                                           "" => ""
lifecycle_rule.0.expiration.4042355233.days: …
```
> Remove s3 expiration setting (that AWS doesnt allow)

- README.md
Fixes my mistake. Terraform does the launch, so this part of the readme is unnecessary.
> Removes erroneous manual launch of SoftNAS instance

- README.md
Doing the global terraform setup from scratch I encountered this error:
```
$ terraform plan -var-file="assets/create_etcd_ebs_snapshot/create_etcd_ebs_snapshots.tfvars" -var-file="assets/prune_ebs_snapshots/vars_prune_ebs_snapshots.tfvars"
* module.ses_domain.aws_route53_record.domain_amazonses_dkim_verification_record: aws_route53_record.domain_amazonses_dkim_verification_record: value of 'count' cannot be computed
```
It sounds like this problem:
https://github.com/hashicorp/terraform/issues/12570
I found this workaround:
```
terraform apply -target aws_route53_record.aws_ses_domain_dkim
```
Perhaps we should merge this fix while we think if it can be fixed in a better way in future.
> Hacky fix for terraform length error

- scripts/label_jupyter_and_rstudio_deployments.sh
This script will add the idleable annotation to any existing rstudio or
jupyter-lab deployments.
Just putting here for reference but really it'll only be run once
I've already run this on dev but... delete the annotation from a deployment and run this again, it will add the annotation back.
> Script: add helper script to put `idleable` annotation on deployed tools

- scripts/invariant_checks/checks/ghosted-by-the-idler.js
- scripts/invariant_checks/checks/index.js
Add a check for deployments the idler disabled but didn't add to the unidler
ingress, this can happens if the idler crashes half way through.
It also takes a --fix flag to automatically fix the unidler ingress in the case
of any failures.
1. Idle yourself or find an idled deployment
1. remove it from the unidler ingresses spec.rules host block
1. run `node index.js` - expect it to tell you this is missing
1. run `node index.js --fix` expect it to fix it
1. run `node index.js` expect it to fix it to pass
1. check the unidler ingress, see that the host block has been re-added
> Invariant Check: Ghosted by the idler

- infra/terraform/modules/user_nfs_softnas/ec2.tf
The AMI is specified explicitly now, rather than using this 'filtering'. The only reference to this code (`data.aws_ami.softnas`) was removed in commit https://github.com/ministryofjustice/analytics-platform-ops/commit/08cf30206797c0c36eac37a28ee4ce023aa586c3
> Remove unused filtering to find the softnas ami

- README.md
Auto-deploy of these pages is documented here: https://auth0.com/docs/extensions/github-deploy#deploy-hosted-pages
I separately added the hosted page source to the analytics-platform-auth0 repo (sorry, I should have done PRs for those):
https://github.com/ministryofjustice/analytics-platform-auth0/tree/alpha/pages
https://github.com/ministryofjustice/analytics-platform-auth0/tree/dev/pages
They deployed fine (dev and alpha):
and the result is the same:
> Mention that Auth0 GitHub Integration also deploys hosted pages too

- infra/terraform/modules/aws_account_logging/s3logs/requirements.txt
Only used by one simple call, so should be fine.
> Update 'requests', due to an advisory

- infra/terraform/modules/aws_account_logging/cloudtrail/requirements.txt
The certifi package specified no longer exists.
certifi is designed so that you always use the latest, so remove the pinning.
Rerun terraform global for a fresh platform.
> Certifi package with that date no longer exists. 

- infra/terraform/platform/main.tf
The use of the `softnas_num_instances` variable was missed as part of the move to workspaces, so both alpha and dev ended up with a single instance configured, but alpha should have two instances. Both alpha and dev `.tfvars` file have the correct number of instances specified, so correct values will be used in both environments.
> Fix terraform softnas_num_instances variable

- infra/terraform/modules/user_nfs_softnas/dns.tf
- infra/terraform/modules/user_nfs_softnas/ebs.tf
- infra/terraform/modules/user_nfs_softnas/ec2.tf
- infra/terraform/modules/user_nfs_softnas/iam.tf
- infra/terraform/modules/user_nfs_softnas/inputs.tf
The SoftNAS terraform module assumes that only one instance would be used, but there will be two during data migration to a new SoftNAS instance, so additional variables have been added to avoid duplication of AWS resource names and DNS collisions.
> Support >1 use of the SoftNAS terraform module

- infra/terraform/modules/aws_account_logging/cloudtrail/setup.cfg
- infra/terraform/modules/aws_account_logging/s3logs/setup.cfg
When running 'terraform apply' (for global), if you have macOS and used Homebrew to install python, then you get this pip install error:
must supply either home or prefix/exec-prefix -- not both
It's discussed here: https://stackoverflow.com/q/24257803
We add setup.cfg file that sets the prefix to nothing and it works around the bug.
Run:
terraform apply -var-file="assets/create_etcd_ebs_snapshot/create_etcd_ebs_snapshots.tfvars" -var-file="assets/prune_ebs_snapshots/vars_prune_ebs_snapshots.tfvars" -target=module.aws_account_logging.null_resource.cloudtrail_install_deps -target=module.aws_account_logging.null_resource.s3logs_install_deps
Title the PR to complete the sentence: "Merging this PR will ..."
> Fix "prefix" error with terraform/pip/osx/brew

- README.md
I believe I just misnoted this before.
With the existing target name, it does `0 to add, 0 to change, 0 to destroy`, before seeing the `count` error message in the next step. With this PR with the corrected target successfully applies 2 changes and the next step works.
> Correct the terraform target name

- infra/terraform/modules/user_nfs_softnas/ebs.tf
Additional EBS volumes had been added via the SoftNAS GUI and were not represented in Terraform; this commit adds them.
EBS volume tags have also been modified to indicate which of the SoftNAS HA pair a given volume is attached to, e.g. `alpha-softnas-0-vol1` and `alpha-softnas-1-vol1` rather than 2x `alpha-softnas-vol1`.
> Add missing SoftNAS EBS volumes to Terraform

- infra/terraform/modules/data_backup/data.tf
The `current` argument to the `aws_region` data provider is now deprecated, as it defaults to the current configured region when no region name or endpoint is defined.
> Remove deprecated `current` arg from `aws_region` data source

- infra/terraform/modules/federated_identity/iam.tf
AWS SAML provider suffixes had been changed from ‘auth0’ to the more generic ‘idp’, but references in auth0 rules and user IAM role trust policies had not been updated to match. This commit reverts that change for now.
> Rename AWS SAML provider to $ENV-auth0

- infra/elasticsearch/templates/cloudtrail.json
- infra/terraform/modules/aws_account_logging/cloudtrail/requirements.txt
__Update Elasticsearch Client__
- We now use Elasticsearch version 6.x
__Update Template__
- Removing deprecated `_all` block
- Template mappings and data can only have one type in ES 6 so removing `_default_` (which will be deprecated)
- Removed superfluous `object` type definition
- Modified conflicting `geo_point` mapping type to `object`
> Cloutrail logs

- infra/terraform/modules/kops_spec/templates/kops.yaml.tmpl
[Trello](https://trello.com/c/YNDTzEIx)
This is to mitigate the [vulnerability](https://medium.com/handy-tech/analysis-of-a-kubernetes-hack-backdooring-through-kubelet-823be5c3d67c) described.
- Disabling anonymous auth and enabling serviceaccount token authentication.
- Disabling Read-Only metrics port
> Kubelet Auth

- infra/terraform/modules/ec2_cluster_autoscaler_policy/data.tf
- infra/terraform/modules/ec2_cluster_autoscaler_policy/iam.tf
- infra/terraform/modules/ec2_cluster_autoscaler_policy/variables.tf
- infra/terraform/platform/main.tf
[Trello](https://trello.com/c/ivZAkPne)
Relates to [PR](https://github.com/ministryofjustice/analytics-platform-config/pull/110)
Small changes to module to:
- Make it a little more explicit by adding another variable for ASGs
- Allow for adding autoscaling groups that do not have similar name as the role the policy will be attached to.
Also allowing Cluster autoscaler to manage the `highmem` autoscaling group
> Scale Highmem to 0

- infra/terraform/global/dynamodb.tf
- infra/terraform/global/main.tf
Enables [state locking with DynamoDB](https://www.terraform.io/docs/backends/state.html) for `global` resources, and creates DynamoDB tables for state locking in `platform-base` and `platform` resources. State locking will be enabled for `platform` and `platform-base` once the [auth0 provider PR](https://github.com/ministryofjustice/analytics-platform-ops/pull/244) has been merged, as an in-progress `apply` of auth0 provider-managed resources currently means that an `apply` in all branches causes an error due to the missing auth0 plugin. In short, it's better to wait for the auth0 provider changes to be merged before proceeding.
> Enable Terraform state locking for `global` and create dynamoDB tables for `platform` and `platform-base`

- infra/terraform/global/iam_upload_users.tf
- infra/terraform/global/s3.tf
- infra/terraform/global/variables.tf
- infra/terraform/modules/data_bucket_upload_user/iam.tf
- infra/terraform/modules/data_bucket_upload_user/outputs.tf
- infra/terraform/modules/data_bucket_upload_user/variables.tf
It creates a new bucket to add lookup tables in to and a new user with write access to those buckets. It also creates a new IAM policy for reading the buckets. 
This is so we can create a concourse job that will copy data from `lookup_` prefixed github repos to this bucket. This can be used for general data so there is a single source for data that is used across departments.
1. There is a bucket called `moj-analytics-lookup-table` created
2. There is a user called `lookup_upload_user` created that can write/delete bucket contents
3. There is a IAM policy called `lookup_s3_readonly` created that can read bucket contents
> Merging this PR will add lookup table user and bucket

- infra/terraform/modules/user_nfs_softnas/ebs.tf
Expanding the SoftNAS storage pool by 500GB.
1. `git checkout expand-softnas-ebs`
2. `cd infra/terraform/platform`
3. `terraform plan -var-file=vars/alpha.tfvars`
_Which should result with this__:
```
~ module.cluster_autoscaler.aws_iam_policy.policy
~ module.control_panel_api.aws_db_instance.control_panel_db
```
> Expand Softnas

- infra/terraform/modules/data_bucket_upload_user/iam.tf
Added roles so the glue job on the lookup tables can assume the `lookups_job_role` so it has required access. Also added a role for uses to assume with read access `lookups_user_role`
1. `lookups_job_role` is created
2.  lookups_user_role is created
3.  Policy changed to allow for logging and cloudwatch
>  Merging this PR will add assume role from glue for the lookup tables job

- infra/terraform/modules/data_bucket_upload_user/iam.tf
Allow lookup user to pass glue job role to glue job
1. `lookup_uploader` user now has `iam:PassRole` for role `arn:aws:iam::*:role/lookups_job_role`
> Allow the lookup upload user to pass role to the aws glue job

- infra/terraform/global/iam_upload_users.tf
- infra/terraform/global/outputs.tf
Adds upload user for HMCTS Azure Platform so they can upload data on to the platform
1. See if user is created and get the outputs from the apply command
> Adds upload user for HMCTS Azure Platform

- infra/terraform/modules/control_panel_api/db.tf
AWS does minor upgrades to RDS instances. Recently it upgraded postgres
from 9.6.6 to 9.6.11. The control panel db was specified exactly to 9.6.6
in terraform, so "terraform apply" wanted to downgrade it again. To avoid
this we simply don't specify the last part of the version and it is happy.
Might as well also explicitly set auto_minor_version_upgrade=True, which is
the default, so no change.
> Postgres was auto-upgraded - avoid terraform complaining

- scripts/remove-idled-label-when-unidled.sh
We have several Deployment which were unidled but whose `idled` label
was not removed.
This script will remove these labels from the `Deployment`s which are
clealy not idled (because they don't have `0` replicas).
**NOTE**: Because this changes only the `Deployment` metadata and not the
pod spec, this will **not** trigger the re-creation of new pods so it
should be safe to run without causing any downtime.
How did this happen?
====================
- the [unidler] uses JSONPatch to remove 2 annotations and this label after
a `Deployment` is unidled
- we introduced a new annotation which is only added by a new version of
the idler
- despite all these patch operations being `remove` operations this patch
fails when the new annotation (or anything) is not already there. This
is frustrating as …
> Script to remove `idled` label when not idled

- infra/terraform/modules/ec2_cluster_autoscaler_policy/iam.tf
Cluster Autoscaler was missing some of the permissions to scale an autoscaling
group from 0.
> Scale highmem from 0

- README.md
This is a setting/value we've had in Auth0 for months now. Just adding it to our list of things to manually configure, as we don't automate Auth0 clients.
> Record that jwt expire setting

- README.md
This seems useful info for someone setting this up for a trial or a real install.
From tests with accelerator platform, it seems the Free plan allows External users to use MFA. It's just when admins want to use MFA for logging into the console when it needs a paid plan.
> adds Auth0 costs note

- README.md
- scripts/auth0connections/.dockerignore
- scripts/auth0connections/.gitignore
- scripts/auth0connections/Dockerfile
- scripts/auth0connections/README.md
- scripts/auth0connections/auth0connections.py
- scripts/auth0connections/connections/nomis/config.yaml
- scripts/auth0connections/connections/nomis/fetchUserProfile.js
- scripts/auth0connections/poetry.lock
- scripts/auth0connections/pyproject.toml
- scripts/auth0connections/values.example.yaml
Document how to create additional auth0 connections (without using `terraform`).
This also adds a script to run, which will create the defined connections
instead of documenting how to do this manually in the auth0 console.
related config change: https://github.com/ministryofjustice/analytics-platform-config/pull/143
cc @sh31 because I know you're working on something similar, maybe this can be removed if your way works for creating connections
> Add script to create Auth0 additional connections

- infra/terraform/global/assets/create_etcd_ebs_snapshot/README.md
Error: `fork/exec /var/task/prune_ebs_snapshots: permission denied: PathError`
Error: `fork/exec /var/task/create_etcd_ebs_snapshot: permission denied: PathError`
I suspect binaries were built incorrectly.
* Tested functions on command line
* Rebuilt binaries `GOOS=linux go build <GO file with main function>`
* Terraform-archived and uploaded zips
> Fix etcd Snapshots

- infra/terraform/global/iam_upload_users.tf
- infra/terraform/global/outputs.tf
terraform plan:
```
+ module.ppas_mdt_upload_user.aws_iam_access_key.system_user
id:                  "<computed>"
encrypted_secret:    "<computed>"
key_fingerprint:     "<computed>"
secret:              "<computed>"
ses_smtp_password:   "<computed>"
status:              "<computed>"
user:                "ppas_mdt_uploader"
+ module.ppas_mdt_upload_user.aws_iam_policy.system_user_s3_writeonly
id:       "<computed>"
arn:      "<computed>"
name:     "ppas_mdt_s3_upload_writeonly"
path:     "/uploaders/ppas/mdt/"
policy:   {
"Statement": [
{
"Action": [
"s3:PutObject",
"s3:ListMultipartUploadParts"
],
"Effect": "Allow",
"Resource": "arn:aws:s3:::mojap-land/ppas/mdt/",
"Sid": ""
}
],
"Version": "2012-10-17"
}
+ module.ppas_mdt_upload_user.aws_iam_user.system
id:              "<computed>"
arn: …
```
> Add upload user for PPAS MDT data

- infra/terraform/global/outputs.tf
- infra/terraform/modules/data_upload_user/iam.tf
Upload user previously only had PutObjewct perms on `aws:arn:::bucket/path/`. Need to add a `*` to the end of it to allow uploads to files/paths within that path.
1.  `*` added to policy bucket arn in PutObject
> Upload user policy

- scripts/auth0connections/connections/nomis/fetchUserProfile.js
This stores the user accessToken in the user profile. This is to allow apps to make calls to the nomis api gateway using the auth token received as part of the oauth2 login flow
https://trello.com/c/ZZ4Cs0tI/250-nomis-login-for-sdt
> Auth0 connections: Fetch user profile script will now store access token in profile

- README.md
* terraform var files were removed a while ago and no longer need specifying.
* VPC flow log lambda functions were added recently
This brings the global terraform more in line with what is running on alpha.
> Update global terraform README - VPC warning and var file refactor

- scripts/invariant_checks/package-lock.json
- scripts/invariant_checks/package.json
In `/scripts/invariant_checks` I ran `npm update` which fixes the security concerns. I ran the script and got the same results before and after the upgrades:
```
~/ap/analytics-platform-ops/scripts/invariant_checks (master *)$ node ./index.js
🔎 starting check: idled-deployments-with-more-than-0-replicas
🔎 starting check: missing-tls-block
🔎 starting check: ghosted-by-the-idler
▶ missing-tls-block: 	✅ PASS
▶ idled-deployments-with-more-than-0-replicas: 	✅ PASS
xxxx-jupyter-lab.tools.alpha.mojanalytics.xyz not in Unidler
...
▶ ghosted-by-the-idler: 	❎ FAIL
```
> Update deps for invariant_checks

- infra/terraform/modules/user_get_parameter/iam.tf
Adds wildcard perms in for region and account as those are both needed for the Parameters
> Params perms requires account and region

- infra/terraform/modules/control_panel_api/role.tf
When creating S3 Buckets in Control Panel, it needs to set public access block by default
> Allow Control Panel to set public access block

- infra/terraform/modules/control_panel_api/role.tf
Add terraform to manage policies for the control panel groups implementation
This is to enable the control panel role to create, delete, attach and detach IAM Managed Policies
> Add terraform to manage policies for the control panel groups implementation

- infra/terraform/modules/ec2_cert_manager_role/iam.tf
[Trello](https://trello.com/c/vK2e5D58)
Cert-Manager version `0.11.0` requires the action: `route53:ListHostedZonesByName`
Title the PR to complete the sentence: "Merging this PR will ..."
> Upgrade Cert Manager

- infra/terraform/modules/control_panel_api/role.tf
While deleting an App from CP I got the following permission error:
> An error occurred (AccessDenied) when calling the GetRole operation: User: arn:aws:sts::XXX:assumed-role/alpha_control_panel_api/XXX-alpha_control_panel_api is not authorized to perform: iam:GetRole on resource: role alpha_app_XXX
Fixes Sentry error: https://sentry.service.dsd.io/mojds/control-panel-api/issues/38606/
Ticket: https://trello.com/c/ymJUXt06
> CP can delete apps' roles

- infra/terraform/modules/user_nfs_softnas/ebs.tf
Volume 6 was already in Terraform but one volume attachment had the "wrong"/different device name.
Volume 7 was previously created manually in AWS Console but now it's in Terraform. **NOTE**: there is only one volume for `softnas-1` as `softnas-0` doesn't seem to be used and Serj thought it was wasteful to create a 2TB volume which is not actually used - that's why these Terraform resources don't have a loop (`count`) unlike the others.
> Terraform import of SoftNAS volume 6 and 7

- infra/terraform/platform/main.tf
From version `~> 1.50` to version `~> 2.45`.
I upgrade this as support for tags on `aws_dlm_lifecycle_policy ` ([introduced in version `2.37.0`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2370-november-18-2019))
`terraform plan` doesn't show any warnings or problems so far.
Part of ticket: https://trello.com/c/4YSbvgFu
> Upgraded Terraform aws provider to version ~> 2.45

- infra/terraform/modules/ebs_snapshots/README.md
- infra/terraform/modules/ebs_snapshots/dlm.tf
- infra/terraform/modules/ebs_snapshots/iam.tf
- infra/terraform/modules/ebs_snapshots/variables.tf
- infra/terraform/platform/main.tf
This is for consistency and it may help future team members to
determine which environment they're snapshotting, if they're used in
production, etc...
Also added `type` to variables (but interestingly Terraform doesn't have a `boolean` type 🤷‍♂ )
**NOTE**: `aws_dlm_lifecycle_policy`'s support for tags was added in
`aws` provider version `2.37.0+`:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2370-november-18-2019
Part of ticket: https://trello.com/c/4YSbvgFu
> ebs_snapshots: Add tags to DLM Policy resources

- infra/terraform/modules/cloudwatch_alerts/README.md
- infra/terraform/modules/cloudwatch_alerts/cloudwatch.tf
- infra/terraform/modules/cloudwatch_alerts/sns.tf
- infra/terraform/modules/cloudwatch_alerts/template-email-sns-stack.json.tpl
- infra/terraform/modules/cloudwatch_alerts/variables.tf
- infra/terraform/modules/user_nfs_softnas/outputs.tf
- infra/terraform/platform/main.tf
Send email if CPU spikes over 80% for 2 five minutes periods in the last
15 minutes.
Unfortunately the `aws_sns_topic_subscription` Terraform resource
doesn't support the `email` protocol:
> Unsupported protocols include the following:
> - email -- delivery of message via SMTP
> - email-json -- delivery of JSON-encoded message via SMTP
>
> These are unsupported because the endpoint needs to be authorized and
> does not generate an ARN until the target email address has been
> validated. This breaks the Terraform model and as a result are not
> currently supported.
Apparently this is because of the manual click to subscribe required.
See: https://www.terraform.io/docs/providers/aws/r/sns_topic_subscription.html
For this reason the module creates a CloudFormation stack which creates
SNS …
> Added cloudwatch_alerts module to monitor SoftNAS

- infra/terraform/modules/kops_spec/templates/kops.yaml.tmpl
Change kops.yaml template in kops_spec terraform module to use the oidc_issuer_url variable for the oidcUsernamePrefix parameter (instead of oidc_provider_url )
The kops.yaml.tmpl template in the kops_spec terraform module currently uses the oidc_provider_url variable to set the oidcUsernamePrefix parameter.
As we do not pass the oidc_provider_url variable into the kops.yaml.tmpl template the terraform plan/apply fails with following error.
* module.kops_spec.data.template_file.kops: 1 error occurred:
* module.kops_spec.data.template_file.kops: data.template_file.kops: failed to render : <template_file>:52,27-44: Unknown variable; There is no variable named "oidc_provider_url
To fix this we can use the existing variable oidc_issuer_url for the oidcUsernamePrefix parameter instead.
This …
> Change kops.yaml template in kops_spec terraform module to use oidc_issuer_url for oidcUsernamePrefix parameter

- infra/terraform/modules/cloudwatch_alerts/cloudwatch.tf
- infra/terraform/modules/cloudwatch_alerts/variables.tf
- infra/terraform/modules/user_nfs_softnas/ec2.tf
- infra/terraform/modules/user_nfs_softnas/inputs.tf
- infra/terraform/platform/main.tf
1. Add a new Cloudwatch alert for Max CPU usage less than 5% for SoftNAS EC2 instances
https://trello.com/c/OBbuQMgu/546-add-softnas-alert-for-5-cpu
2. Change high CPU threshold on Cloudwatch alert from 80% to 70% for SoftNAS EC2 instances
https://trello.com/c/zxqpfTKQ/541-adjust-cloudwatch-alert-values
3. Enabled detailed monitoring on SoftNAS EC2 instances
> Add Cloudwatch alert for low CPU and change high alert threshold to 70% for SoftNAS EC2

- git-crypt/README.md
- git-crypt/rotate-gpg-keys.sh
* it's convenient for data engineers to be able to download the script without cloning the repo
* improved description of what the rotate script does
> git-crypt rotate doc tweaks following usage

- infra/terraform/global/iam_upload_users.tf
- infra/terraform/global/outputs.tf
Merging this PR will add a user for upload into the ppas workforce-planning dir, as requested by DF and JC.
This is based on the previous PR: https://github.com/ministryofjustice/analytics-platform-ops/pull/281/files
I've gone ahead and applied this:
```
terraform apply -target module.ppas_workforce_planning_upload_user.aws_iam_access_key.system_user
terraform apply -target module.ppas_workforce_planning_upload_user.aws_iam_policy.system_user_s3_writeonly
terraform apply -target module.ppas_workforce_planning_upload_user.aws_iam_user_policy_attachment.system_user_s3_upload
```
> Add upload user for the ppas workforce-planning dir

- infra/terraform/modules/asg_cloudwatch_alerts/README.md
- infra/terraform/modules/asg_cloudwatch_alerts/cloudwatch.tf
- infra/terraform/modules/asg_cloudwatch_alerts/variables.tf
- infra/terraform/platform/main.tf
We want to send an alert of the CPU usage on the Kubernetes master nodes is high for a sustained period.
As the Kubernetes master nodes are in AutoScaling groups we need to put the monitoring on the Auto scaling groups rather than the individual EC2 instances as the instance IDs of these could change.
- Add a module to create an alert rule for high CPU usage in an Autoscaling group
- Use this module to create alerts for each of the Auto scaling groups used by the Kubernetes master nodes.
> Add Cloudwatch alerts for CPU usage of Kubernetes master instances

- infra/terraform/modules/elb_cloudwatch_alerts/cloudwatch.tf
Elastic Load balancers don't send any metrics for surge queue length if they don't receive any requests in the sampling period.
Therefore it makes sense to treat missing metrics for surge queue length as Not breaching the alarms to prevent receiving false alarms.
> Change to treat missing surge queue data as not breaching to prevent false alarms

- infra/terraform/modules/asg_cloudwatch_alerts/cloudwatch.tf
The alarm for Desired instances for Auto scaling groups should use Maximum for the metric instead of Count (which is not a valid metric)
> Correct metric for desired instances to use Maximum instead of Count

- infra/terraform/modules/control_panel_api/role.tf
- scripts/version_buckets.py
This PR complements [this PR in the control panel](https://github.com/ministryofjustice/analytics-platform-control-panel/pull/816) for ensuring S3 buckets are versioned by default and have a life cycle so that non-current versions of files are set to glacier storage after 30 days.
**This script should only be run once, when the control panel PR is merged and deployed.**
The related ticket in Trello is here: https://trello.com/c/g5NFH4Mi/588-s3-bucket-backups-versioning
This script was run against a single "alpha" S3 bucket and the end result was verified by @andylightfoot.
> Add a one-shot script to bulk update alpha S3 buckets to be versioned.

- infra/terraform/modules/data_buckets/iam.tf
- infra/terraform/modules/data_buckets/main.tf
Because it's not been used in a long time:
* No console creds
* Access keys last used 2017.
* Access Advisor agrees there's been no access in 400 days
And there's nothing about this user elsewhere in our code.
> Remove 'shared_analyst' IAM User

- git-crypt/README.md
We're transitioning away from storing gpg keys in https://github.com/ministryofjustice/analytical-platform-public-keys
Related PR: https://github.com/ministryofjustice/analytical-platform-public-keys/pull/9
> We should get GPG keys from GitHub.

- infra/terraform/modules/cloudwatch_alerts/cloudwatch.tf
Add a missing line to the check - has been applied successfully.
> Adding missing statistic line to EC2 status check

- infra/terraform/global/iam_upload_users.tf
- infra/terraform/global/s3.tf
- infra/terraform/global/variables.tf
This bucket used to be maintained by the Analytical Platform, but now is
maintained by the data engineering team. This has led to a situation
where both Pulumi and Terraform are trying to manage the same resource.
This PR removes it from Terraform. We will also remove it from state as
part of this PR so Terraform forgets about the resource and Pulumi can
continue to maintain it.
> Remove uploads bucket that is maintained by Data Engineering

- infra/terraform/platform-base/main.tf
The env parameter had been removed from the modules but not the calling code.
> Remove env parameter as has been removed from these modules

- infra/terraform/global/cloudtrail.tf
- infra/terraform/global/dns.tf
- infra/terraform/global/dynamodb.tf
- infra/terraform/global/ebs_snapshots.tf
- infra/terraform/global/main.tf
- infra/terraform/global/modules/aws_account_logging/s3.tf
- infra/terraform/global/modules/aws_account_logging/variables.tf
- infra/terraform/global/modules/iam_list_roles/iam.tf
- infra/terraform/global/modules/iam_list_roles/variables.tf
- infra/terraform/global/modules/lambda_mgmt/CHANGELOG.md
- infra/terraform/global/modules/lambda_mgmt/README.md
- infra/terraform/global/modules/lambda_mgmt/iam.tf
- infra/terraform/global/modules/lambda_mgmt/lambda.tf
- infra/terraform/global/modules/lambda_mgmt/variables.tf
- infra/terraform/global/modules/ses_domain/main.tf
- infra/terraform/global/modules/ses_domain/variables.tf
- infra/terraform/global/s3.tf
This PR;
- Adds the mandatory tags to all available resources
- Add descriptions to variables so `terraform-docs` can generate the table for the `lambda_mgmt` module correctly 
- Adds types to variables so variables don't just let anything through
- Uses Terraform 0.12 handling of arrays to pull back an array from `aws_route53_zone.global.name_servers` rather than specifying all the name servers in the array manually. This makes moving between name servers/ regions easier.
> Add tags to resources & tidy up the lambda_mgmt module

- infra/elasticsearch/README.md
- infra/elasticsearch/iam.tf
- infra/elasticsearch/provider.tf
- infra/elasticsearch/s3.tf
- infra/elasticsearch/terraform.tfvars.json
- infra/elasticsearch/variables.tf
- infra/elasticsearch/versions.tf
Upgrade Elasticsearch Terraform to 0.13
This prepares for ElasticSearch module for moving it to the main Terraform
> Upgrade Elasticsearch Terraform to 0.13

- scripts/upgrade_s3_permissions.py
This script gives existing users of the control panel the permissions they need to work with versioned S3 buckets.
1. Test on a `dev` user and ensure the error message for the related s3 bucket no longer appears in the web based admin page.
Trello reference: https://trello.com/c/HqDQMr6s/843-fix-s3-user-permissions
> Add script to update s3 versioning related permissions for existing users.

- infra/terraform/platform/main.tf
Define environment specific variables for bastion_launch_template_name and bastion_iam_policy_name so that we avoid name conflicts.
> use environment specific resource names for the bastions

- infra/terraform/platform/main.tf
Switch the bastion cloudwatch monitoring/alerts to point at the load balancer for the new bastions
> Point bastion monitoring at new bastion lbs

- infra/terraform/platform/data.tf
- infra/terraform/platform/main.tf
The old bastion monitoring was using ELB metrics. We are now using an NLB instead so we need to change the monitoring.
As it just requires one resource, I have defined the single resource rather than using/creating a module.
- Remove old bastion monitoring
- Add monitoring for number of healthy hosts in Bastion NLB target groups
> Update bastion monitoring as we now use an NLB

- README.md
Github Deployment is no longer an option in auth0, instead it is
recommended to use github actions to deploy changes to the rules.
> Note that github deployment for rules is deprecated
