.gitignore
infra/terraform/modules/data_buckets/s3.tf

See: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

Enforce S3 encryption on upload

---

charts/rstudio/Chart.yaml
charts/rstudio/templates/deployment.yml

See: https://github.com/ministryofjustice/analytics-platform-rstudio/pull/4

RStudio: Using new Docker image with PDF generation dependencies

---

charts/init-user/templates/user-secrets.yml
jenkinsfiles/create_user.groovy
jenkinsfiles/create_user.sh

This secret is in the user's namespace.

Storing username/email and fullname in user secrets

---

charts/config-user/.helmignore
charts/config-user/Chart.yaml
charts/config-user/templates/_helpers.tpl
charts/config-user/templates/configmap-git-config.yaml
charts/config-user/templates/job-config-git.yaml
charts/config-user/values.yaml
jenkinsfiles/config_user.groovy
jenkinsfiles/config_user.sh

This will set up things like git config and other user-specific
things (in the future).
For the moment this will just create the ~/.gitconfig file.

config-user helm chart

---

charts/rstudio/values.yaml

See: https://github.com/ministryofjustice/analytics-platform-rstudio/pull/6

Dev env: Testing RStudio docker image with webshot/phantomjs

---

infra/terraform/global/iam.tf
infra/terraform/global/outputs.tf

Adds an IAM user with SES email sending credentials, for use by Auth0 to send emails.

Added IAM user for Auth0 SES email sending

---

infra/terraform/environments/dev/main.tf
infra/terraform/modules/control_panel_db/resources.tf
infra/terraform/modules/control_panel_db/variables.tf

* Add AWS RDS instance for Control Panel app

Set up the control panel RDS database

---

infra/terraform/environments/alpha/main.tf
infra/terraform/environments/alpha/outputs.tf
infra/terraform/environments/dev/outputs.tf
infra/terraform/modules/control_panel_api/outputs.tf

This will create the CP-API DB and its IAM role.
I also added the DB host and the IAM role to the outputs.
Part of: https://trello.com/c/8Y086TqG/407-cp-api-deploy-to-alpha

Alpha: Uncomment 'control_panel_api' module

---

config/grafana/dashboards/platform-users.json

I'm assuming it's normal for an update to this to change pretty much every line...? Maybe just because it hasn't been updated in 7 months...?
This is just pasted out of the Grafana UI as it stands right now.

Update grafana config for platform users

---

README.md
infra/install_helm_charts.sh

Change mojanalytics helm repo URL to new S3 hosted repository

Use S3 hosted Helm repo

---

infra/elasticsearch/README.md
infra/elasticsearch/iam.tf
infra/elasticsearch/s3.tf
infra/elasticsearch/templates/cloudtrail.json
infra/elasticsearch/templates/logstash-apps.json
infra/elasticsearch/templates/s3logs.json
infra/elasticsearch/variables.tf

Sets up AWS resources for an elasticsearch repository with an s3
backend.

Elasticsearch: Backup

---

scripts/upgrade_tools_releases.sh

Upgrades helm tool releases specified with the `-a` flag to their latest chart
version.
Deployed in alpha

Helm: Upgrade Releases Script

---

scripts/ingress_custom_columns.txt

Usage (command is also in the file as comment)
```
kubectl get ingress --all-namespaces -o=custom-columns-file=scripts/ingress_custom_columns.txt
```

Added custom-columns-file to debug ingress problems

---

README.md

By documenting what we did, even if someone wants to use a different service, it is listed as something that needs doing.

Add elastic search (saas) setup

---

infra/terraform/platform/main.tf

This policy is seen on dev and alpha and is needed.

Add a policy that is needed by controlpanel

---

README.md
config/helm/tiller.yml

This is how I got helm to work, by deploying this config that was already in this repo.
Deploy the cluster up to this point and see if helm commands work.

add helm rbac setup

---

README.md

I added the set-up for Auth0 tenant and initial application. We should convert this to terraform this at some point.
Follow the instructions and check you get what is seen in dev/alpha in auth0 dashboard.

Initial auth0 setup added

---

.gitignore
scripts/invariant_checks/.eslintrc.js
scripts/invariant_checks/checks/idled-deployments-with-more-than-0-replicas.js
scripts/invariant_checks/checks/index.js
scripts/invariant_checks/checks/missing-tls-block.js
scripts/invariant_checks/index.js
scripts/invariant_checks/package-lock.json
scripts/invariant_checks/package.json

Since we have an .eslint config, I've updated the code to pass that lint check
without warnings or errors.

Invariant Checks Linter Fixes

---

README.md

I added some minimal docs for setting these:
* ses_ap_email_identity_arn
* trusted_entity and hostedzoneid_arn

More info on environment terraform settings

---

README.md

Almost too minor to be worth mentioning, but I've done the edit now, so might as well keep it.

Mention splash screens in the setup

---

README.md

Make it easy for the person creating the cluster to send a message to dev colleagues how to get the kubectl creds.

adds a way to communicate the kubectl creds

---

infra/terraform/global/iam_upload_users.tf
infra/terraform/global/main.tf

- separates upload user resources into separate file to improve comprehension somewhat
- adds upload user for LAA's CLA application

Add LAA upload IAM user

---

infra/terraform/modules/ec2_cluster_autoscaler_policy/README.md
infra/terraform/modules/ec2_cluster_autoscaler_policy/iam.tf
infra/terraform/modules/ec2_cluster_autoscaler_policy/variables.tf
infra/terraform/platform/main.tf
infra/terraform/platform/variables.tf

Module to provision IAM resources for [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler)
See [Permissions](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#permissions)

Cluster AutoScaler Policy

---

infra/terraform/modules/log_pruning/prune_logs/requirements.txt

Upgrade to version which actually fixes vulnerability

Upgrade to PyYAML 4.2b1 to fix vulnerability

---

infra/terraform/global/outputs.tf

Adds lookup tables to global outputs
1. Lookup creds will be in outputs

Add lookup outputs globally

---

scripts/set-tools-host-labels.sh

This is to simplify unidling logic by leveraging labels.

Script to add `host` label to tools k8s resources

---

infra/terraform/modules/kops_spec/templates/kops.yaml.tmpl

- Added the oidcUsernamePrefix option introduced in kops 1.9 followed by a PR from Aldo:
https://github.com/kubernetes/kops/pull/4085

Add oidcUsernamePrefix option

---

infra/terraform/modules/control_panel_api/role.tf

Gives the control panel ability to create parameters
Changed the IAM policy to add statement for creating Params

Add parameter permissions to control panel

---

infra/terraform/modules/data_upload_user/iam.tf

This is how hmcts_upload_user is already configured manually. The other uploaders didn't work.
```
$ terraform plan |landscape
~ module.hmpps_nomis_upload_user.aws_iam_policy.system_user_s3_writeonly
policy:   "Action": [
"s3:PutObject",
"s3:ListMultipartUploadParts"
],
"Effect": "Allow",
-      "Resource": "arn:aws:s3:::mojap-land/hmpps/nomis/",
+      "Resource": "arn:aws:s3:::mojap-land/hmpps/nomis/*",
"Sid": ""
}
],
"Version": "2012-10-17"
}
~ module.hmpps_oasys_upload_user.aws_iam_policy.system_user_s3_writeonly
policy:   "Action": [
"s3:PutObject",
"s3:ListMultipartUploadParts"
],
"Effect": "Allow",
-      "Resource": "arn:aws:s3:::mojap-land/hmpps/oasys/",
+      "Resource": "arn:aws:s3:::mojap-land/hmpps/oasys/*",
"Sid": ""
}
],
"Version": "2012-10-17"
}
~ …
```

Upload users need an IAM wildcard to be able to write files

---

infra/terraform/modules/user_get_parameter/iam.tf
infra/terraform/modules/user_get_parameter/outputs.tf
infra/terraform/modules/user_get_parameter/variables.tf
infra/terraform/platform/main.tf
infra/terraform/platform/outputs.tf

Allows concourse to get parameter to add to webapp
Added module to create user that can get and decrypt parameters

Add get parameter user for concourse

---

infra/terraform/modules/control_panel_api/role.tf

Updated cpanel parameter iam policy fo give it proper perms.

Update param iam policy for control panel

---

infra/terraform/global/iam_upload_users.tf
infra/terraform/global/outputs.tf

Adds prisoner-money upload user

Add prisoner-money upload user

---

scripts/set_deployment_image_tag.sh

Script to modify image tags.  Useful for rolling out
versions or just serving as an example. As is will perform the migration on
rstudio.
Gated with `dry-run` flag for no-op runs to what will be changed if
run.
Title the PR to complete the sentence: "Merging this PR will ..."
Execute the script and answer `y` to invoke a dry run. You will see output for deployments that will be affected. i.e. __Does not match __ the image defined in the script.
In dev, that will be my deployment

Set Image Tag

---

infra/terraform/modules/user_nfs_softnas/ebs.tf

Extending SoftNAS storage pool and importing into terraform state.

SoftNAS: Add disk

---

infra/install_helm_charts.sh

Not sure we use this install script any more. And I have not tested this install line, but useful to be more correct than before...

We use metrics-server not heapster now

---

.github/CODEOWNERS
scripts/invariant_checks/package-lock.json

This resolves most of the npm issues
lodash is of course still broken and unpatched

Run npm audit fix

---

infra/terraform/modules/control_panel_api/role.tf

Rebase of https://github.com/ministryofjustice/analytics-platform-ops/pull/271

Remove temporary role

---

git-crypt/README.md

Improve the git-crypt documentation

tweaks to git-crypt docs

---

git-crypt/README.md

* Fix the "gpg --edit-key" command for trusting a key - it wasn't saving it previously.
* When adding someones gpg key, check in the public-keys repo first
* Add section to explain the files you see in git-crypt - there seems to be a need to work out the status of a repo.
* An easier way to edit the branch protection rules compared to deleting it entirely.

git-crypt instructions - fix for trusting key

---

infra/terraform/modules/cloudwatch_alerts/cloudwatch.tf

Title the PR to complete the sentence: "Merging this PR will ..."
Add an alert on the softnas instance if it shows as unhealthy.

Add ec2 softnas alert

---

scripts/update-webapps-fluent-bit-image-to-ECR.sh

This is to reduce the number of pull requests we're making to DockerHub
which is causing problems because of the newly introduced rate limites.
I also ran this through https://www.shellcheck.net/
Thanks to @damacus for the help with the Bash function.
https://trello.com/c/Izxt87HF

Script to update webapps to use fluent-bit image in ECR

---

README.md
infra/terraform/platform/main.tf

Now the old bastions have been retired we can rename the new bastions to "bastion.${terraform.workspace}.mojanalytics.xyz"

Change DNS name of bastions and update README
